### ISSUE TITLE
SyntaxError: The requested module '@sajenid/aksara.js' does not provide an export named 'LatinKeAksara'

### ISSUE THREAD

**Issue by Bintang73** [sajenid/aksara.js#2]
import { LatinKeAksara } from '@sajenid/aksara.js'
         ^^^^^^^^^^^^^
SyntaxError: The requested module '@sajenid/aksara.js' does not provide an export named 'LatinKeAksara'
[90m    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)[39m
[90m    at async ModuleJob.run (internal/modules/esm/module_job.js:143:5)[39m
[90m    at async Loader.import (internal/modules/esm/loader.js:165:24)[39m
[90m    at async Object.loadESM (internal/process/esm_loader.js:68:5)[39m

**Comment by junwatu** [comment]
Fix ada di versi  [v1.0.0-beta.6](https://github.com/sajenid/aksara.js/packages/285742)

Trims. 🙏
